### PR TITLE
Darrenge vale kremlin

### PR DESCRIPTION
**Pull request by darrenge**
Double checked with Barry on whether he is ok with this and he is.

### CODE REVIEW

**Comment by msprotz** [comment]
It seems like this doesn't use the latest version of the code I had written in the original github issue. Have you tried it out? This was just an (untested) sketch...

Thanks,

Jonathan

**Comment by darrenge** [comment]
My mistake ... I tested it out before you updated it. My mistake was that I thought the new build of Kremlin after Everest build would push out what we needed. I will update with your updated sketch and retest it.

**Comment by darrenge** [comment]
Updated with your new suggestions. The code was correct ... just needed to add a couple packages to the Linux agent docker container (informed Irina which ones were needed). Barry is aware of changes to be needed for NoVerify which will be in Kremlin

**Comment by msprotz** [comment]
Excellent. Thanks!

**Comment by darrenge** [comment]
One of these days, I will do it right the first time. I'll keep at it ...

**Pull request merged**
